version: '3'

services:
  api:
    build: .
    container_name: api-sqlinjection-node-mysql
    command: npm run start
    depends_on:
      - mysqldb
    ports: 
      - 3001:3001
    volumes:
      - .:/usr/src/hospital-app

  mysqldb:
    container_name: db-sqlinjection-node-mysql
    env_file: .env
    environment:
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
    expose:
      - 3306
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      #- ./db/backup/files/:/data_backup/

volumes: 
  db-config:
  db-data: